const colors = {
  light: {
    text: "#1A1A2E",
    tint: "#C8A574",
    background: "#F8F5F0",
    foreground: "#1A1A2E",
    card: "#FFFFFF",
    cardForeground: "#1A1A2E",
    primary: "#C8A574",
    primaryForeground: "#FFFFFF",
    secondary: "#F0EDE8",
    secondaryForeground: "#1A1A2E",
    muted: "#F0EDE8",
    mutedForeground: "#7A7A8A",
    accent: "#C8A574",
    accentForeground: "#FFFFFF",
    destructive: "#E53935",
    destructiveForeground: "#ffffff",
    border: "#E8E4DC",
    input: "#F0EDE8",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#C8A574",
    background: "#0A0A0A",
    foreground: "#FFFFFF",
    card: "#141414",
    cardForeground: "#FFFFFF",
    primary: "#C8A574",
    primaryForeground: "#FFFFFF",
    secondary: "#1E1E1E",
    secondaryForeground: "#FFFFFF",
    muted: "#1E1E1E",
    mutedForeground: "#888888",
    accent: "#C8A574",
    accentForeground: "#FFFFFF",
    destructive: "#E53935",
    destructiveForeground: "#FFFFFF",
    border: "#2A2A2A",
    input: "#1E1E1E",
  },
  radius: 20,
};

export default colors;
