// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/category-split/CategorySplit.tsx": () => import("../components/mockups/category-split/CategorySplit.tsx"),
  "./components/mockups/home-screen/HomeScreen.tsx": () => import("../components/mockups/home-screen/HomeScreen.tsx"),
  "./components/mockups/provider-skills/ProviderSkills.tsx": () => import("../components/mockups/provider-skills/ProviderSkills.tsx")
};
