import AsyncStorage from "@react-native-async-storage/async-storage";
import React, { createContext, useContext, useEffect, useState } from "react";

export type Lang = "ar" | "en" | "he";

const LANG_STORAGE_KEY = "khadma.lang";

export const translations = {
  ar: {
    dir: "rtl" as const,
    flag: "🇸🇦",
    label: "العربية",
    tabs: {
      more: "المزيد",
      services: "خدماتي",
      messages: "الرسائل",
      home: "الرئيسية",
      orders: "طلباتي",
      profile: "حسابي"
    },
    langPicker: {
      title: "اختر لغتك",
      subtitle: "اختر اللغة المناسبة لك",
      arabic: "العربية",
      english: "English",
      hebrew: "עברית",
      rtl: "من اليمين لليسار",
      ltr: "Left to Right",
    },
    onboarding: {
      skip: "تخطي",
      next: "التالي",
      startNow: "ابدأ الآن",
      slide1Label: "اختر طريقة استخدامك",
      slide1Desc: "مزود خدمة أو عميل",
      slide2Label: "اكتشف المزودين",
      slide2Desc: "أفضل المزودين بالقرب منك",
      slide3Label: "تصفح الخدمات",
      slide3Desc: "مجموعة واسعة من الخدمات المنزلية",
      slide4Label: "احجز بسهولة",
      slide4Desc: "خطوات بسيطة لحجز خدمتك",
    },
    role: {
      appName: "Khadma",
      welcome: "مرحباً بك",
      subtitle: "اختر نوع الحساب المناسب لك",
      provider: "مقدم خدمة",
      providerDesc: "انضم كمقدم خدمة وقدم خدماتك للعملاء",
      customer: "طالب خدمة",
      customerDesc: "اطلب الخدمات التي تحتاجها بسهولة وأمان",
      contact: "تواصل معنا",
      contactSub: "نحن هنا لمساعدتك",
    },
    auth: {
      appName: "Khadma",
      welcomeBack: "أهلاً بعودتك",
      signIn: "تسجيل الدخول",
      signInSub: "أدخل بياناتك للمتابعة",
      signUp: "إنشاء حساب",
      signUpSub: "سجّل للبدء باستخدام خدمة",
      verifyEmail: "تأكيد البريد الإلكتروني",
      verifySub: "أدخل رمز التحقق المُرسل إلى بريدك",
      email: "البريد الإلكتروني",
      password: "كلمة المرور",
      code: "رمز التحقق",
      enter: "دخول",
      verify: "تحقق ودخول",
      create: "إنشاء حساب",
      sendCode: "إرسال الرمز",
      sending: "جارٍ الإرسال...",
      verifying: "جارٍ التحقق...",
      resend: "إعادة إرسال الرمز",
      or: "أو",
      signInGoogle: "الدخول عبر Google",
      signUpGoogle: "التسجيل عبر Google",
      hasAccount: "لديك حساب بالفعل؟",
      noAccount: "ليس لديك حساب؟",
      loginLink: "تسجيل الدخول",
      registerLink: "إنشاء حساب",
      back: "رجوع",
      changeEmail: "تغيير البريد الإلكتروني",
      completeProfile: "أكمل ملفك الشخصي",
      fullName: "الاسم الكامل",
      namePlaceholder: "أدخل اسمك",
      howToUse: "كيف تريد الاستخدام؟",
      customer: "طالب خدمة",
      provider: "مقدم خدمة",
      commissionTitle: "عمولة المنصة",
      commissionText: "تحصل المنصة على عمولة قدرها 10% من قيمة كل خدمة تنجزها. يُخصم هذا المبلغ تلقائياً من أرباحك وتظهر التفاصيل في صفحة الأرباح.",
      commissionAgree: "أوافق على خصم عمولة 10% من أرباحي",
      continue: "متابعة",
      saving: "جارٍ الحفظ...",
      logout: "تسجيل الخروج",
      nameError: "الرجاء إدخال اسمك",
      commissionError: "يجب الموافقة على عمولة المنصة (10%) للمتابعة",
      agreementsError: "يجب الموافقة على جميع البنود للمتابعة",
      privacyAgree: "أوافق على سياسة الخصوصية",
      privacyRead: "قراءة",
      pledgeAgree: "أتعهد بصحة بياناتي والالتزام بتقديم الخدمات بمهنية واحترام والالتزام بالمواعيد المتفق عليها",
      privacyTitle: "سياسة الخصوصية",
      privacyBody:
        "تطبيق «خدمة» يربط بين مقدّمي الخدمات المنزلية والشخصية والعملاء في شمال البلاد. خصوصيتك مهمة لنا، وفيما يلي كيف نتعامل مع بياناتك:\n\n" +
        "١) المعلومات التي نجمعها: الاسم، رقم الهاتف، البريد الإلكتروني، العنوان والموقع الجغرافي، ووثائق التحقّق للمزوّدين مثل شهادة الترخيص وبطاقة الهوية.\n\n" +
        "٢) كيف نستخدمها: لإنشاء حسابك، وتوصيلك بأقرب مزوّد مناسب، ومعالجة الطلبات والمدفوعات، والتواصل معك بشأن خدمتك.\n\n" +
        "٣) مشاركة البيانات: نشارك فقط المعلومات الضرورية لإتمام الخدمة (مثل اسمك وموقعك التقريبي مع المزوّد)، ولا نبيع بياناتك لأي طرف ثالث.\n\n" +
        "٤) الموقع الجغرافي: يُستخدم لعرض المزوّدين القريبين وتحديد منطقة الخدمة، ويمكنك إيقافه من إعدادات جهازك.\n\n" +
        "٥) وثائق التحقّق: تُحفظ بشكل آمن وتُستخدم لمراجعة طلب الانضمام فقط، وتُحذف بعد اتخاذ القرار النهائي.\n\n" +
        "٦) حقوقك: يمكنك تعديل بياناتك أو طلب حذف حسابك في أي وقت.\n\n" +
        "٧) التواصل: لأي استفسار حول الخصوصية تواصل معنا عبر صفحة «اتصل بنا» داخل التطبيق.",
      privacyClose: "إغلاق",
      provisionError: "تعذّر إنشاء الملف الشخصي، حاول مرة أخرى",
      serverError: "تعذّر الاتصال بالخادم، تحقّق من اتصالك",
      invalidCode: "الرمز غير صحيح أو منتهي، حاول مرة أخرى",
      loginFailed: "تعذّر إكمال تسجيل الدخول، حاول مرة أخرى",
      signupFailed: "تعذّر إكمال إنشاء الحساب، حاول مرة أخرى لاحقاً",
      verifyFailed: "تعذّر التحقق من الرمز، حاول مرة أخرى",
      finalizeFailed: "تعذّر إكمال الدخول، حاول مرة أخرى",
    },
    layout: {
      errorTitle: "تعذّر تحميل حسابك",
      errorBody: "حدث خطأ أثناء الاتصال بالخادم. تحقّق من اتصالك وحاول مرة أخرى.",
      retry: "إعادة المحاولة",
      signOut: "تسجيل الخروج",
    },
    home: {
      appName: "Khadma",
      goodEvening: "مساء الخير",
      weAreHere: "نحن هنا لخدمتك باحتراف",
      currentLocation: "موقعك الحالي",
      update: "تحديث",
      locationDenied: "تم رفض إذن الوصول إلى الموقع. فعّله من إعدادات الجهاز للمتابعة.",
      openSettings: "فتح الإعدادات",
      locationError: "تعذّر تحديد موقعك الحالي. تأكد من تفعيل خدمة الموقع وحاول مرة أخرى.",
      searchService: "ابحث عن خدمة...",
      viewAll: "عرض الكل",
      categories: "الأقسام",
      professionalServices: "خدمات احترافية",
      highQuality: "بجودة عالية وأسعار مناسبة",
      bookNow: "احجز الآن",
      painting: "الدهانات",
      maintenance: "صيانة البيوت",
      electricity: "كهرباء",
      plumbing: "سباكة",
      furniture: "أثاث وديكور",
      cars: "خدمات السيارات",
      cleaning: "تنظيف",
      ac: "تكييف",
      carpentry: "نجارة",
      appliances: "صيانة الأجهزة",
      pest_control: "مكافحة حشرات",
      landscaping: "تنسيق حدائق",
      moving: "نقل ونقل",
      other: "خدمة أخرى",
    },
    services: {
      title: "الخدمات",
      beauty: "الجمال",
      home: "المنزل",
      maintenance: "الصيانة",
      added: "مضاف",
      add: "اطلب",
      min: "د",
      currency: "ر.س",
      empty: "لا توجد خدمات",
    },
    req: {
      newTitle: "اطلب خدمة",
      newSub: "صف ما تحتاجه واحصل على عروض من المزودين",
      chooseService: "اختر الخدمة",
      details: "التفاصيل",
      descLabel: "وصف الطلب",
      descPlaceholder: "اكتب تفاصيل ما تحتاجه...",
      descRequired: "الرجاء كتابة وصف الطلب",
      addressRequired: "الرجاء إدخال العنوان",
      phoneRequired: "الرجاء إدخال رقم هاتف صالح",
      photo: "صورة (اختياري)",
      addPhoto: "أضف صورة",
      changePhoto: "تغيير الصورة",
      removePhoto: "إزالة",
      uploading: "جارٍ رفع الصورة...",
      location: "الموقع",
      useGps: "استخدام موقعي الحالي",
      locating: "جارٍ تحديد الموقع...",
      located: "تم تحديد الموقع",
      addressPlaceholder: "العنوان أو وصف الموقع",
      priceRange: "نطاق السعر المتوقع",
      priceMin: "من",
      priceMax: "إلى",
      preferredTime: "الوقت المفضل",
      asap: "في أقرب وقت",
      todayEvening: "اليوم مساءً",
      tomorrowMorning: "غداً صباحاً",
      tomorrowEvening: "غداً مساءً",
      timeAsap: "في أقرب وقت",
      timeTodayEve: "اليوم مساءً",
      timeTomMorning: "غداً صباحاً",
      timeTomEve: "غداً مساءً",
      submit: "إرسال الطلب",
      submitting: "جارٍ الإرسال...",
      created: "تم إرسال طلبك",
      createdMsg: "سيتواصل معك مزودو الخدمة بعروضهم قريباً",
      viewRequest: "عرض الطلب",
      ok: "حسناً",
      selectServiceFirst: "اختر خدمة أولاً",
      locationRequired: "يرجى إدخال اسم البلدة أو المدينة",
      paymentLabel: "طريقة الدفع (اختياري)",
      payOnSite: "الدفع عند الوصول (نقداً)",
      error: "تعذّر إرسال الطلب. حاول مرة أخرى.",
      locationPermission: "يرجى السماح بالوصول للموقع",
      locationFailed: "تعذّر تحديد الموقع",
      submitFailed: "تعذّر إرسال الطلب. حاول مرة أخرى.",
      currency: "ر.س",
      mediaSectionTitle: "إرفاق صورة أو فيديو (مطلوب)",
      mediaSectionSub: "أرفق ملف واحد على الأقل لتوضيح الطلب",
      mediaRequired: "يرجى إرفاق صورة أو فيديو للطلب",
      photoBtn: "صورة",
      videoBtn: "فيديو",
      uploadingMedia: "جارٍ رفع الملف...",
      sparePartsLabel: "شامل قطع غيار",
      sparePartsHint: "اختياري — حدّد إذا كانت الخدمة تشمل قطع الغيار",
      mediaPermission: "نحتاج إذن الوصول إلى الوسائط",
      stepLocation: "أين تحتاج الخدمة؟",
      stepDescription: "ماذا تحتاج أن يُنجَز؟",
      stepTime: "متى تحتاجها؟",
      stepPrice: "ما ميزانيتك؟",
      next: "التالي",
      back: "رجوع",
      confirm: "تأكيد وإرسال",
      review: "مراجعة",
      changeService: "تغيير الخدمة",
      request: "طلب",
      // My Requests
      myTitle: "طلباتي",
      current: "الطلبات الحالية",
      past: "الطلبات السابقة",
      empty: "لا توجد طلبات بعد",
      emptySub: "اطلب خدمتك الأولى الآن",
      newRequest: "طلب جديد",
      // Detail
      requestDetails: "تفاصيل الطلب",
      offers: "العروض",
      offersFor: "العروض المقدمة",
      noOffers: "لا توجد عروض بعد",
      noOffersSub: "بانتظار عروض من مزودي الخدمة",
      offersError: "تعذّر تحميل العروض",
      offersRetry: "إعادة المحاولة",
      offerCount: "عرض",
      chooseOffer: "اختيار هذا العرض",
      choosing: "جارٍ القبول...",
      accepted: "مقبول",
      rejected: "مرفوض",
      pendingOffer: "بانتظار الرد",
      chosenProvider: "المزود المختار",
      scheduledFor: "الموعد",
      rating: "التقييم",
      noRating: "جديد",
      offerMessage: "رسالة",
      availableTime: "الوقت المتاح",
      duration: "المدة",
      provider: "مزود الخدمة",
      confirmAccept: "قبول العرض",
      confirmAcceptMsg: "سيتم تعيين هذا المزود لتنفيذ الخدمة ورفض باقي العروض.",
      cancelRequest: "إلغاء الطلب",
      cancelConfirm: "هل أنت متأكد من إلغاء هذا الطلب؟",
      markComplete: "تأكيد إكمال الخدمة",
      completeConfirm: "هل تم إنجاز الخدمة بنجاح؟",
      cancel: "إلغاء",
      // status
      statusPending: "بانتظار العروض",
      statusActive: "تم القبول",
      statusInProgress: "قيد التنفيذ",
      statusCompleted: "مكتمل",
      statusCancelled: "ملغي",
      // timeline
      tlCreated: "تم إنشاء الطلب",
      tlActive: "تم اختيار المزود",
      tlCompleted: "اكتملت الخدمة",
    },
    profile: {
      title: "حسابي",
      name: "مستخدم خدمة",
      verified: "موثّق",
      completed: "طلب مكتمل",
      active: "طلب نشط",
      total: "إجمالي الطلبات",
      accountSection: "الحساب",
      nameLabel: "الاسم",
      phoneLabel: "رقم الجوال",
      addresses: "عناويني",
      addressTitle: "عنواني",
      addressDesc: "هذا الموقع محفوظ ويُستخدم تلقائياً في كل طلب جديد، ولا يتغيّر إلا إذا غيّرته بنفسك.",
      addressLabel: "العنوان",
      addressPlaceholder: "مثال: شفاعمرو، الحي الشرقي، شارع ١٢",
      addressEmpty: "لم تحدّد عنواناً بعد",
      addressSaved: "تم حفظ عنوانك",
      saveAddress: "حفظ العنوان",
      editProfile: "تعديل الملف الشخصي",
      save: "حفظ",
      saving: "جارٍ الحفظ...",
      nameHint: "الاسم اختياري",
      phoneHint: "يمكنك تغيير رقم هاتفك في أي وقت",
      updated: "تم تحديث ملفك الشخصي",
      updateFailed: "تعذّر التحديث، حاول مجدداً",
      prefs: "التفضيلات",
      notifications: "الإشعارات",
      language: "اللغة",
      theme: "المظهر",
      dark: "داكن",
      light: "فاتح",
      support: "المساعدة",
      faq: "الأسئلة الشائعة",
      contact: "تواصل معنا",
      rate: "قيّم التطبيق",
      logout: "تسجيل الخروج",
      logoutConfirm: "هل أنت متأكد من تسجيل الخروج؟",
      logoutTitle: "تسجيل الخروج",
      cancel: "إلغاء",
      version: "خدمة • الإصدار 1.0.0",
      settings: "الإعدادات",
      privacy: "سياسة الخصوصية",
      terms: "شروط الاستخدام",
      about: "عن التطبيق",
    },
    review: {
      rateProvider: "قيّم المزود",
      title: "تقييم الخدمة",
      subtitle: "كيف كانت تجربتك مع هذا المزود؟",
      commentLabel: "تعليقك (اختياري)",
      commentPlaceholder: "شاركنا رأيك في الخدمة...",
      submit: "إرسال التقييم",
      submitting: "جارٍ الإرسال...",
      submitted: "تم إرسال تقييمك",
      thanks: "شكراً لتقييمك!",
      alreadyReviewed: "لقد قيّمت هذه الخدمة",
      yourReview: "تقييمك",
      selectStars: "اختر عدد النجوم",
      error: "تعذّر إرسال التقييم. حاول مرة أخرى.",
    },
    notif: {
      title: "الإشعارات",
      empty: "لا توجد إشعارات",
      emptySub: "ستظهر هنا تحديثات طلباتك وعروضك",
      markAllRead: "تعليم الكل كمقروء",
      error: "تعذّر تحميل الإشعارات",
      retry: "إعادة المحاولة",
    },
    chat: {
      title: "المحادثات",
      empty: "لا توجد محادثات",
      emptySub: "ستظهر هنا محادثاتك مع مزودي الخدمة",
      error: "تعذّر تحميل المحادثات",
      threadError: "تعذّر تحميل المحادثة",
      retry: "إعادة المحاولة",
      inputPlaceholder: "اكتب رسالتك...",
      send: "إرسال",
      messageProvider: "مراسلة المزود",
      messageCustomer: "مراسلة العميل",
      startConversation: "ابدأ المحادثة بإرسال رسالة",
      requestLabel: "طلب",
      requestFallback: "طلب",
      customerPhone: "رقم العميل",
      providerPhone: "رقم مقدم الخدمة",
      callCustomer: "اتصل بالعميل",
      callProvider: "اتصل بمقدم الخدمة",
      contactAfterAccept: "يظهر رقم الهاتف بعد قبول الطلب",
    },
    contact: {
      title: "تواصل معنا",
      subtitle: "نسعد بسماع ملاحظاتك واستفساراتك",
      nameLabel: "الاسم",
      emailLabel: "البريد الإلكتروني (اختياري)",
      subjectLabel: "الموضوع (اختياري)",
      messageLabel: "رسالتك",
      namePlaceholder: "اسمك",
      emailPlaceholder: "you@example.com",
      subjectPlaceholder: "موضوع الرسالة",
      messagePlaceholder: "اكتب رسالتك هنا...",
      submit: "إرسال",
      submitting: "جارٍ الإرسال...",
      sent: "تم إرسال رسالتك",
      sentMsg: "سنتواصل معك في أقرب وقت ممكن",
      error: "تعذّر إرسال الرسالة. حاول مرة أخرى.",
      required: "يرجى إدخال الاسم والرسالة",
    },
    rate: {
      title: "قيّم التطبيق",
      subtitle: "رأيك يساعدنا على تحسين خدمة",
      tapToRate: "اضغط على النجوم للتقييم",
      commentLabel: "ملاحظاتك (اختياري)",
      commentPlaceholder: "ما الذي يعجبك أو يمكننا تحسينه؟",
      submit: "إرسال التقييم",
      submitting: "جارٍ الإرسال...",
      sent: "شكراً لك!",
      sentMsg: "تم إرسال تقييمك بنجاح",
      error: "تعذّر إرسال التقييم. حاول مرة أخرى.",
      selectStars: "يرجى اختيار التقييم أولاً",
      appRatingSubject: "تقييم التطبيق",
    },
    ranking: {
      title: "أفضل المزودين",
      subtitle: "الأعلى تقييماً من عملائنا",
      empty: "لا يوجد مزودون بعد",
      reviews: "تقييم",
      jobs: "طلب",
      noRating: "جديد",
    },
    providerOnboarding: {
      title: "سجّل كمقدم خدمة",
      subtitle: "أكمل بياناتك لبدء استقبال الطلبات",
      serviceLabel: "الخدمة التي تقدّمها",
      cityLabel: "البلدة التي تخدمها",
      cityPlaceholder: "اختر بلدتك",
      phoneLabel: "رقم الجوال",
      phonePlaceholder: "05X XXX XXXX",
      experienceLabel: "سنوات الخبرة",
      experiencePlaceholder: "مثال: 5",
      bioLabel: "نبذة عنك وماذا تقدّم",
      bioPlaceholder: "اكتب تفاصيل خدمتك، تخصصك، وما يميّزك...",
      locationLabel: "موقعك (اختياري)",
      locationBtn: "تحديد موقعي الحالي",
      locationDone: "تم تحديد موقعك",
      submit: "إرسال طلب التسجيل",
      errorService: "اختر الخدمة التي تقدّمها",
      errorCity: "اختر البلدة التي تخدمها",
      errorPhone: "أدخل رقم الجوال",
      errorSubmit: "تعذّر إرسال الطلب. حاول مرة أخرى.",
      errorLocation: "تعذّر الحصول على الموقع. فعّل خدمة الموقع وحاول مجدداً.",
      errorCustomSkill: "حدث خطأ في إضافة المهارة. حاول مرة أخرى.",
      logout: "تسجيل الخروج",
      skillsLabel: "المهارات التي تتقنها",
      addCustomSkill: "مهارة مخصصة",
      customSkillTitle: "إضافة مهارة مخصصة",
      customSkillPlaceholder: "اسم المهارة...",
      cityModalTitle: "اختر البلدة",
      cityModalSearch: "ابحث عن بلدة...",
      cityModalEmpty: "لا توجد نتائج",
      skillsPlaceholder: "اختر خدماتك...",
      skillsSelectedSuffix: "خدمات مختارة",
      skillsModalTitle: "اختر خدماتك",
      skillsModalSearch: "ابحث عن خدمة...",
      skillsModalEmpty: "لا توجد نتائج",
      skillsModalDone: "تم",
      addressLabel: "عنوان السكن",
      addressPlaceholder: "المدينة، الشارع، رقم المنزل",
      errorAddress: "أدخل عنوان السكن",
      docsLabel: "المستندات المطلوبة",
      docsHint: "تُستخدم للتحقق فقط وتُحذف بعد المراجعة",
      docOsekPaturLabel: "شهادة عوسك باتور (إعفاء)",
      docOsekMursheLabel: "شهادة عوسك مرشيه (مرخّص)",
      docIdLabel: "صورة الهوية أو الرخصة",
      docRequired: "مطلوب",
      docOptional: "اختياري",
      docPick: "إرفاق ملف",
      docReplace: "استبدال الملف",
      docOnFile: "تم الإرفاق",
      docSaved: "ملف محفوظ لدى الإدارة",
      docUploading: "جارٍ الرفع...",
      errorDocs: "أرفق جميع المستندات المطلوبة",
      docUploadError: "تعذّر رفع الملف. حاول مرة أخرى.",
      reviewNoteTitle: "ملاحظة من الإدارة",
      resubmit: "إعادة إرسال الطلب",
      resubmitTitle: "تحديث بياناتك",
      resubmitSubtitle: "حدّث المعلومات أو المستندات المطلوبة ثم أعد الإرسال",
    },
    providerDashboard: {
      title: "لوحتي",
      requests: "الطلبات",
      greeting: "أهلاً {name}",
      guest: "بك",
      availOn: "متاح",
      availOff: "غير متاح",
      receiveRequests: "استقبال الطلبات",
      visibleNow: "أنت ظاهر للعملاء الآن",
      activateAvail: "فعّل التوفر لاستقبال الطلبات",
      workHours: "ساعات العمل",
      from: "من",
      to: "إلى",
      saveHours: "حفظ ساعات العمل",
      completed: "مكتمل",
      active: "جارٍ",
      earnings: "ر.س",
      openRequests: "طلبات مفتوحة",
      seeAll: "عرض الكل",
      activateAvailHint: "فعّل التوفر لرؤية الطلبات القريبة",
      noMatching: "لا توجد طلبات مطابقة لخدمتك حالياً",
      request: "طلب",
    },
    providerProfile: {
      title: "حسابي",
      provider: "مقدم خدمة",
      noRating: "لا تقييم بعد",
      service: "خدمة مكتملة",
      avgRating: "متوسط التقييم",
      status: "الحالة",
      statusOpen: "متاح",
      statusClosed: "مغلق",
      account: "الحساب",
      edit: "تعديل",
      name: "الاسم",
      serviceLabel: "الخدمة",
      phone: "رقم الجوال",
      address: "العنوان",
      location: "الموقع",
      locationSet: "تم تحديد الموقع",
      locationNotSet: "غير محدّد",
      workHours: "ساعات العمل",
      bio: "نبذة",
      logout: "تسجيل الخروج",
      logoutConfirm: "هل أنت متأكد من تسجيل الخروج؟",
      version: "خدمة · مقدم خدمة · الإصدار 1.0.0",
      editTitle: "تعديل الحساب",
      fullName: "اسمك الكامل",
      phonePlaceholder: "05X XXX XXXX",
      chooseService: "الخدمة التي تقدّمها",
      addressPlaceholder: "الحي، المدينة، تفاصيل العنوان",
      detectLocation: "تحديد موقعي الحالي",
      locationDetected: "تم تحديد موقعك الحالي",
      saveChanges: "حفظ التغييرات",
      errorName: "أدخل الاسم.",
      errorService: "اختر الخدمة التي تقدّمها.",
      errorPhone: "أدخل رقم الجوال.",
      errorSave: "تعذّر حفظ التغييرات. حاول مرة أخرى.",
      errorLocation: "تعذّر الحصول على الموقع. فعّل خدمة الموقع وحاول مجدداً.",
      avatarFallback: "خد",
      commissionSection: "عمولة المنصة",
      commissionRate: "نسبة العمولة",
      commissionDesc: "تحصل المنصة على عمولة قدرها 10% من قيمة كل خدمة تنجزها، تُخصم تلقائياً من أرباحك.",
      commissionAgreedLabel: "تاريخ الموافقة",
      commissionNotRecorded: "غير مسجّل",
    },
    providerRequests: {
      title: "الطلبات",
      tabAvailable: "متاحة",
      tabOffers: "عروضي",
      tabJobs: "أعمالي",
      activateFirst: "فعّل التوفر من الصفحة الرئيسية لاستقبال الطلبات القريبة",
      noNearby: "لا توجد طلبات قريبة مطابقة لخدمتك حالياً",
      offerSent: "تم تقديم عرض",
      sendOffer: "تقديم عرض",
      noOffers: "لم تقدّم أي عروض بعد",
      messageCustomer: "مراسلة العميل",
      noJobs: "لا توجد أعمال مُسندة إليك بعد",
      startJob: "بدء التنفيذ",
      completeJob: "إنهاء الخدمة",
      navigate: "بدء الملاحة المباشرة",
      offerTitle: "تقديم عرض",
      priceLabel: "السعر (ر.س)",
      durationLabel: "المدة المتوقعة (اختياري)",
      durationPlaceholder: "مثال: ساعة واحدة",
      timeLabel: "وقت التوفّر",
      messageLabel: "رسالة (اختياري)",
      messagePlaceholder: "عرّف العميل بنفسك أو أضف تفاصيل...",
      submitOffer: "إرسال العرض",
      enterPrice: "أدخل سعراً صحيحاً.",
      offerError: "تعذّر إرسال العرض. حاول مرة أخرى.",
      offerAvailError: "فعّل التوفر أولاً لتتمكن من تقديم العروض.",
      offerUnavailable: "فعّل التوفر أولاً لتتمكن من تقديم العروض.",
      offerInvalidPrice: "أدخل سعراً صحيحاً.",
      offerSubmitFailed: "تعذّر إرسال العرض. حاول مرة أخرى.",
      pending: "بانتظار الرد",
      accepted: "مقبول",
      rejected: "مرفوض",
      completed: "مكتمل",
      inProgress: "قيد التنفيذ",
      jobAccepted: "تم القبول",
      budget: "ميزانية العميل",
      onSitePayment: "الدفع عند الوصول (نقداً)",
      request: "طلب",
    },
    providerEarnings: {
      title: "أرباحي",
      netLabel: "صافي الأرباح (بعد العمولة)",
      servicesDone: "خدمة مكتملة",
      grossIncome: "إجمالي الدخل",
      platformFee: "عمولة المنصة (10%)",
      netEarnings: "صافي الأرباح",
      commissionOwed: "عمولة مستحقة للمنصة",
      commissionBreakdown: "إجمالي العمولة {total} ر.س · المسدّد {settled} ر.س",
      noCommission: "لا توجد عمولة مستحقة عليك حالياً",
      threshold: "الحد المسموح: {threshold} ر.س",
      commissionWarning: "تجاوزت حد العمولة المسموح. لن تتمكن من استقبال طلبات جديدة حتى تسدّد المبلغ المستحق عبر إدارة المنصة.",
      history: "سجل المدفوعات",
      noEarnings: "لا توجد أرباح بعد. أكمل خدماتك لتظهر هنا.",
      from: "من",
      currency: "ر.س",
      request: "طلب",
    },
    navigate: {
      arrived: "لقد وصلت إلى موقع العميل",
      continueTo: "تابع نحو موقع العميل",
      after: "بعد",
      arrivalTime: "الوصول",
      estimatedTime: "زمن تقريبي",
      remainingDistance: "المسافة المتبقية",
      voiceNav: "ملاحة صوتية",
      noLocation: "لا يتوفر موقع لهذا الطلب",
      back: "رجوع",
      permDenied: "يجب السماح بالوصول للموقع لبدء الملاحة",
      locating: "جارٍ تحديد موقعك...",
      distance: "المسافة",
      eta: "وقت الوصول",
      approxTime: "وقت تقريبي",
    },
    providers: {
      title: "المزودين",
      latest: "الأحدث",
      price: "السعر",
      nearest: "الأقرب",
      topRated: "الأعلى تقييماً",
      reviews: "تقييم",
      km: "كم",
      filter: "فلترة",
      count: "{{count}} مقدم خدمة",
      mapView: "عرض الخريطة",
      empty: "لا يوجد مقدمين خدمة حالياً",
      changeLocation: "تغيير الموقع",
      availableNow: "متاح الآن",
      general: "صيانة عامة",
      cityFallback: "الناصرة",
      viewProfile: "عرض الملف الشخصي",
      requestService: "طلب الخدمة",
      searchPlaceholder: "ابحث عن مزود خدمة...",
    },
    privacy: {
      title: "سياسة الخصوصية",
      content: "نحرص على خصوصيتك. لا نبيع بياناتك. نستخدمها فقط لتقديم الخدمة والتواصل بينك وبين مزودي الخدمة.",
    },
    terms: {
      title: "شروط الاستخدام",
      content: "باستخدام خدمة، توافق على التواصل بحسن نية، وتقييم المزودين بعد الانتهاء، والدفع عند الاستلام إذا وافقت على ذلك.",
    },
    about: {
      title: "عن التطبيق",
      content: "خدمة — تطبيق ذكي لحجز الخدمات المنزلية والشخصية في بلدات شمال إسرائيل. نربطك بأفضل المزودين بثقة وأمان.",
    },
  },
  en: {
    dir: "ltr" as const,
    flag: "🇬🇧",
    label: "English",
    tabs: {
      more: "More",
      services: "Services",
      messages: "Messages",
      home: "Home",
      orders: "Orders",
      profile: "Profile"
    },
    langPicker: {
      title: "Choose Your Language",
      subtitle: "Select the language that suits you",
      arabic: "Arabic",
      english: "English",
      hebrew: "Hebrew",
      rtl: "Right to Left",
      ltr: "Left to Right",
    },
    onboarding: {
      skip: "Skip",
      next: "Next",
      startNow: "Start Now",
      slide1Label: "Choose Your Path",
      slide1Desc: "Service Provider or Customer",
      slide2Label: "Discover Providers",
      slide2Desc: "Best providers near you",
      slide3Label: "Browse Services",
      slide3Desc: "Wide range of home services",
      slide4Label: "Book Easily",
      slide4Desc: "Simple steps to book your service",
    },
    role: {
      appName: "Khadma",
      welcome: "Welcome",
      subtitle: "Choose the account type that suits you",
      provider: "Service Provider",
      providerDesc: "Join as a provider and offer your services to customers",
      customer: "Service Seeker",
      customerDesc: "Request the services you need easily and safely",
      contact: "Contact us",
      contactSub: "We are here to help",
    },
    auth: {
      appName: "Khadma",
      welcomeBack: "Welcome back",
      signIn: "Sign In",
      signInSub: "Enter your details to continue",
      signUp: "Create Account",
      signUpSub: "Sign up to start using Khadma",
      verifyEmail: "Verify Email",
      verifySub: "Enter the verification code sent to your email",
      email: "Email",
      password: "Password",
      code: "Verification Code",
      enter: "Enter",
      verify: "Verify & Enter",
      create: "Create Account",
      sendCode: "Send Code",
      sending: "Sending...",
      verifying: "Verifying...",
      resend: "Resend Code",
      or: "Or",
      signInGoogle: "Sign in with Google",
      signUpGoogle: "Sign up with Google",
      hasAccount: "Already have an account?",
      noAccount: "Don't have an account?",
      loginLink: "Sign In",
      registerLink: "Create Account",
      back: "Back",
      changeEmail: "Change Email",
      completeProfile: "Complete your Profile",
      fullName: "Full Name",
      namePlaceholder: "Enter your name",
      howToUse: "How do you want to use it?",
      customer: "Service Seeker",
      provider: "Service Provider",
      commissionTitle: "Platform Commission",
      commissionText: "The platform takes a 10% commission from each service completed. This amount is automatically deducted from your earnings and details appear in the earnings page.",
      commissionAgree: "I agree to a 10% commission deduction from my earnings",
      continue: "Continue",
      saving: "Saving...",
      logout: "Logout",
      nameError: "Please enter your name",
      commissionError: "You must agree to the platform commission (10%) to continue",
      agreementsError: "You must agree to all terms to continue",
      privacyAgree: "I agree to the Privacy Policy",
      privacyRead: "Read",
      pledgeAgree: "I confirm my information is accurate and pledge to provide services professionally, respectfully, and on the agreed schedule",
      privacyTitle: "Privacy Policy",
      privacyBody:
        "Khadma connects providers of home and personal services with customers in northern Israel. Your privacy matters to us, and here is how we handle your data:\n\n" +
        "1) Information we collect: name, phone number, email, address and location, and verification documents for providers such as a business license and ID.\n\n" +
        "2) How we use it: to create your account, match you with the nearest suitable provider, process requests and payments, and contact you about your service.\n\n" +
        "3) Data sharing: we share only what is needed to complete a service (such as your name and approximate location with the provider). We never sell your data to third parties.\n\n" +
        "4) Location: used to show nearby providers and define service areas. You can disable it from your device settings.\n\n" +
        "5) Verification documents: stored securely, used only to review a join request, and deleted after the final decision.\n\n" +
        "6) Your rights: you can edit your information or request deletion of your account at any time.\n\n" +
        "7) Contact: for any privacy question, reach us through the \"Contact us\" page in the app.",
      privacyClose: "Close",
      provisionError: "Could not create profile, try again",
      serverError: "Could not connect to server, check your connection",
      invalidCode: "Invalid or expired code, try again",
      loginFailed: "Could not complete sign in, try again",
      signupFailed: "Could not complete sign up, try again later",
      verifyFailed: "Could not verify code, try again",
      finalizeFailed: "Could not complete sign in, try again",
    },
    home: {
      appName: "Khadma",
      goodEvening: "Good Evening",
      weAreHere: "We are here to serve you professionally",
      currentLocation: "Your current location",
      update: "Update",
      locationDenied: "Location permission was denied. Enable it in your device settings to continue.",
      openSettings: "Open settings",
      locationError: "Couldn't determine your location. Make sure location services are on and try again.",
      searchService: "Search for a service...",
      viewAll: "View All",
      categories: "Categories",
      professionalServices: "Professional Services",
      highQuality: "High quality at fair prices",
      bookNow: "Book Now",
      painting: "Painting",
      maintenance: "Home Maintenance",
      electricity: "Electricity",
      plumbing: "Plumbing",
      furniture: "Furniture & Decor",
      cars: "Car Services",
      cleaning: "Cleaning",
      ac: "AC",
      carpentry: "Carpentry",
      appliances: "Appliances",
      pest_control: "Pest Control",
      landscaping: "Landscaping",
      moving: "Moving",
      other: "Other Services",
    },
    services: {
      title: "Services",
      beauty: "Beauty",
      home: "Home",
      maintenance: "Repairs",
      added: "Added",
      add: "Request",
      min: "min",
      currency: "SAR",
      empty: "No services found",
    },
    req: {
      newTitle: "Request a Service",
      newSub: "Describe what you need and get offers from providers",
      chooseService: "Choose a service",
      details: "Details",
      descLabel: "Request description",
      descPlaceholder: "Describe what you need...",
      photo: "Photo (optional)",
      addPhoto: "Add a photo",
      changePhoto: "Change photo",
      removePhoto: "Remove",
      uploading: "Uploading photo...",
      location: "Location",
      useGps: "Use my current location",
      locating: "Locating...",
      located: "Location set",
      addressPlaceholder: "Address or location notes",
      priceRange: "Expected price range",
      priceMin: "From",
      priceMax: "To",
      preferredTime: "Preferred time",
      timeAsap: "As soon as possible",
      timeTodayEve: "Today evening",
      timeTomMorning: "Tomorrow morning",
      timeTomEve: "Tomorrow evening",
      submit: "Submit Request",
      submitting: "Submitting...",
      created: "Request submitted",
      createdMsg: "Providers will reach out with their offers soon",
      viewRequest: "View Request",
      ok: "OK",
      selectServiceFirst: "Choose a service first",
      locationRequired: "Please enter your town or city name",
      phoneRequired: "Please enter a valid phone number",
      paymentLabel: "Payment method (optional)",
      payOnSite: "Pay on arrival (cash)",
      error: "Could not submit the request. Try again.",
      locationPermission: "Location permission is required to continue",
      locationFailed: "Could not determine location",
      submitFailed: "Failed to submit request. Try again.",
      currency: "SAR",
      mediaSectionTitle: "Attach Image or Video (Required)",
      mediaSectionSub: "Attach at least one file to clarify the request",
      mediaRequired: "Please attach an image or video for the request",
      photoBtn: "Photo",
      videoBtn: "Video",
      uploadingMedia: "Uploading file...",
      sparePartsLabel: "Includes spare parts",
      sparePartsHint: "Optional — check if the job includes spare parts",
      mediaPermission: "Media access permission is required",
      stepLocation: "Where do you need the service?",
      stepDescription: "What needs to be done?",
      stepTime: "When do you need it?",
      stepPrice: "What's your budget?",
      next: "Next",
      back: "Back",
      confirm: "Confirm & Submit",
      review: "Review",
      changeService: "Change Service",
      request: "Request",
      myTitle: "My Requests",
      current: "Active requests",
      past: "Past requests",
      empty: "No requests yet",
      emptySub: "Request your first service now",
      newRequest: "New Request",
      requestDetails: "Request Details",
      offers: "Offers",
      offersFor: "Offers received",
      noOffers: "No offers yet",
      noOffersSub: "Waiting for providers to send offers",
      offersError: "Couldn't load offers",
      offersRetry: "Retry",
      offerCount: "offer(s)",
      chooseOffer: "Choose this offer",
      choosing: "Accepting...",
      accepted: "Accepted",
      rejected: "Rejected",
      pendingOffer: "Pending",
      chosenProvider: "Chosen provider",
      scheduledFor: "Scheduled",
      rating: "Rating",
      noRating: "New",
      offerMessage: "Message",
      availableTime: "Available time",
      duration: "Duration",
      provider: "Provider",
      confirmAccept: "Accept offer",
      confirmAcceptMsg: "This provider will be assigned and other offers rejected.",
      cancelRequest: "Cancel request",
      cancelConfirm: "Are you sure you want to cancel this request?",
      markComplete: "Mark as completed",
      completeConfirm: "Has the service been completed successfully?",
      cancel: "Cancel",
      statusPending: "Awaiting offers",
      statusActive: "Accepted",
      statusInProgress: "In progress",
      statusCompleted: "Completed",
      statusCancelled: "Cancelled",
      tlCreated: "Request created",
      tlActive: "Provider chosen",
      tlCompleted: "Service completed",
    },
    profile: {
      title: "My Profile",
      name: "Khadma User",
      verified: "Verified",
      completed: "Completed",
      active: "Active",
      total: "Total requests",
      accountSection: "Account",
      nameLabel: "Name",
      phoneLabel: "Phone",
      addresses: "My Addresses",
      addressTitle: "My Address",
      addressDesc: "This location is saved and used automatically for every new request. It won't change unless you change it yourself.",
      addressLabel: "Address",
      addressPlaceholder: "e.g. Shefa-'Amr, East District, 12 Main St",
      addressEmpty: "No address set yet",
      addressSaved: "Your address was saved",
      saveAddress: "Save address",
      editProfile: "Edit Profile",
      save: "Save",
      saving: "Saving...",
      nameHint: "Name is optional",
      phoneHint: "You can change your phone number anytime",
      updated: "Your profile has been updated",
      updateFailed: "Update failed, please try again",
      prefs: "Preferences",
      notifications: "Notifications",
      language: "Language",
      theme: "Appearance",
      dark: "Dark",
      light: "Light",
      support: "Support",
      faq: "FAQ",
      contact: "Contact Us",
      rate: "Rate the App",
      logout: "Log Out",
      logoutConfirm: "Are you sure you want to log out?",
      logoutTitle: "Log Out",
      cancel: "Cancel",
      version: "Khadma • Version 1.0.0",
      settings: "Settings",
      privacy: "Privacy Policy",
      terms: "Terms of Use",
      about: "About App",
    },
    review: {
      rateProvider: "Rate provider",
      title: "Rate the service",
      subtitle: "How was your experience with this provider?",
      commentLabel: "Your comment (optional)",
      commentPlaceholder: "Share your thoughts about the service...",
      submit: "Submit review",
      submitting: "Submitting...",
      submitted: "Review submitted",
      thanks: "Thanks for your review!",
      alreadyReviewed: "You already reviewed this service",
      yourReview: "Your review",
      selectStars: "Select a rating",
      error: "Could not submit the review. Try again.",
    },
    notif: {
      title: "Notifications",
      empty: "No notifications",
      emptySub: "Updates about your requests and offers appear here",
      markAllRead: "Mark all read",
      error: "Couldn't load notifications",
      retry: "Retry",
    },
    chat: {
      title: "Messages",
      empty: "No conversations",
      emptySub: "Your chats with service providers appear here",
      error: "Couldn't load conversations",
      threadError: "Couldn't load conversation",
      retry: "Retry",
      inputPlaceholder: "Type a message...",
      send: "Send",
      messageProvider: "Message provider",
      messageCustomer: "Message customer",
      startConversation: "Start the conversation by sending a message",
      requestLabel: "Request",
      requestFallback: "Request",
      customerPhone: "Customer phone",
      providerPhone: "Provider phone",
      callCustomer: "Call customer",
      callProvider: "Call provider",
      contactAfterAccept: "Phone number is shown after the request is accepted",
    },
    contact: {
      title: "Contact Us",
      subtitle: "We'd love to hear your feedback and questions",
      nameLabel: "Name",
      emailLabel: "Email (optional)",
      subjectLabel: "Subject (optional)",
      messageLabel: "Your message",
      namePlaceholder: "Your name",
      emailPlaceholder: "you@example.com",
      subjectPlaceholder: "Message subject",
      messagePlaceholder: "Write your message here...",
      submit: "Send",
      submitting: "Sending...",
      sent: "Message sent",
      sentMsg: "We'll get back to you as soon as possible",
      error: "Could not send the message. Try again.",
      required: "Please enter your name and message",
    },
    rate: {
      title: "Rate the App",
      subtitle: "Your feedback helps us improve Khadma",
      tapToRate: "Tap the stars to rate",
      commentLabel: "Your feedback (optional)",
      commentPlaceholder: "What do you like or what can we improve?",
      submit: "Submit rating",
      submitting: "Submitting...",
      sent: "Thank you!",
      sentMsg: "Your rating was submitted successfully",
      error: "Could not submit the rating. Try again.",
      selectStars: "Please select a rating first",
      appRatingSubject: "App rating",
    },
    ranking: {
      title: "Top Providers",
      subtitle: "Highest rated by our customers",
      empty: "No providers yet",
      reviews: "reviews",
      jobs: "jobs",
      noRating: "New",
    },
    providerOnboarding: {
      title: "Register as a Provider",
      subtitle: "Complete your info to start receiving requests",
      serviceLabel: "Service you offer",
      cityLabel: "Town you serve",
      cityPlaceholder: "Select your town",
      phoneLabel: "Phone number",
      phonePlaceholder: "05X XXX XXXX",
      experienceLabel: "Years of experience",
      experiencePlaceholder: "e.g. 5",
      bioLabel: "About you and what you offer",
      bioPlaceholder: "Describe your service, specialty, and what makes you unique...",
      locationLabel: "Your location (optional)",
      locationBtn: "Detect my current location",
      locationDone: "Location set",
      submit: "Submit Registration",
      errorService: "Please select the service you offer",
      errorCity: "Please select the town you serve",
      errorPhone: "Please enter your phone number",
      errorSubmit: "Could not submit the request. Try again.",
      errorLocation: "Could not get location. Enable location services and try again.",
      errorCustomSkill: "Error adding skill. Try again.",
      logout: "Log Out",
      skillsLabel: "Skills you offer",
      addCustomSkill: "Custom Skill",
      customSkillTitle: "Add Custom Skill",
      customSkillPlaceholder: "Skill name...",
      cityModalTitle: "Select Town",
      cityModalSearch: "Search for a town...",
      cityModalEmpty: "No results",
      skillsPlaceholder: "Select your services...",
      skillsSelectedSuffix: "services selected",
      skillsModalTitle: "Select your services",
      skillsModalSearch: "Search for a service...",
      skillsModalEmpty: "No results",
      skillsModalDone: "Done",
      addressLabel: "Residential address",
      addressPlaceholder: "City, street, house number",
      errorAddress: "Please enter your residential address",
      docsLabel: "Required documents",
      docsHint: "Used for verification only and deleted after review",
      docOsekPaturLabel: "Osek Patur certificate",
      docOsekMursheLabel: "Osek Murshe certificate",
      docIdLabel: "ID or license photo",
      docRequired: "Required",
      docOptional: "Optional",
      docPick: "Attach file",
      docReplace: "Replace file",
      docOnFile: "Attached",
      docSaved: "On file with admin",
      docUploading: "Uploading...",
      errorDocs: "Please attach all required documents",
      docUploadError: "Could not upload the file. Try again.",
      reviewNoteTitle: "Note from the admin",
      resubmit: "Resubmit application",
      resubmitTitle: "Update your info",
      resubmitSubtitle: "Update the requested info or documents, then resubmit",
    },
    providerDashboard: {
      title: "Dashboard",
      requests: "Requests",
      greeting: "Hello {name}",
      guest: "Guest",
      availOn: "Available",
      availOff: "Unavailable",
      receiveRequests: "Receive Requests",
      visibleNow: "You are visible to customers now",
      activateAvail: "Enable availability to receive requests",
      workHours: "Work Hours",
      from: "From",
      to: "To",
      saveHours: "Save Work Hours",
      completed: "Completed",
      active: "Active",
      earnings: "SAR",
      openRequests: "Open Requests",
      seeAll: "See All",
      activateAvailHint: "Enable availability to see nearby requests",
      noMatching: "No matching requests for your service right now",
      request: "Request",
    },
    providerProfile: {
      title: "My Profile",
      provider: "Service Provider",
      noRating: "No ratings yet",
      service: "Completed",
      avgRating: "Average Rating",
      status: "Status",
      statusOpen: "Open",
      statusClosed: "Closed",
      account: "Account",
      edit: "Edit",
      name: "Name",
      serviceLabel: "Service",
      phone: "Phone",
      address: "Address",
      location: "Location",
      locationSet: "Location set",
      locationNotSet: "Not set",
      workHours: "Work Hours",
      bio: "About",
      logout: "Log Out",
      logoutConfirm: "Are you sure you want to log out?",
      version: "Khadma \u00b7 Service Provider \u00b7 Version 1.0.0",
      editTitle: "Edit Account",
      fullName: "Your full name",
      phonePlaceholder: "05X XXX XXXX",
      chooseService: "Service you offer",
      addressPlaceholder: "District, city, address details",
      detectLocation: "Detect my current location",
      locationDetected: "Current location detected",
      saveChanges: "Save Changes",
      errorName: "Please enter your name.",
      errorService: "Please select the service you offer.",
      errorPhone: "Please enter your phone number.",
      errorSave: "Could not save changes. Try again.",
      errorLocation: "Could not get location. Enable location services and try again.",
      avatarFallback: "KP",
      commissionSection: "Platform Commission",
      commissionRate: "Commission Rate",
      commissionDesc: "The platform takes a 10% commission from each service you complete, deducted automatically from your earnings.",
      commissionAgreedLabel: "Agreed On",
      commissionNotRecorded: "Not recorded",
    },
    providerRequests: {
      title: "Requests",
      tabAvailable: "Available",
      tabOffers: "My Offers",
      tabJobs: "My Jobs",
      activateFirst: "Enable availability from the home page to receive nearby requests",
      noNearby: "No nearby requests matching your service right now",
      offerSent: "Offer sent",
      sendOffer: "Send Offer",
      noOffers: "You haven't sent any offers yet",
      messageCustomer: "Message Customer",
      noJobs: "No jobs assigned to you yet",
      startJob: "Start Work",
      completeJob: "Complete Service",
      navigate: "Start Navigation",
      offerTitle: "Send Offer",
      priceLabel: "Price (SAR)",
      durationLabel: "Expected Duration (optional)",
      durationPlaceholder: "e.g. one hour",
      timeLabel: "Availability Time",
      messageLabel: "Message (optional)",
      messagePlaceholder: "Introduce yourself or add details...",
      submitOffer: "Submit Offer",
      enterPrice: "Please enter a valid price.",
      offerError: "Could not send offer. Try again.",
      offerAvailError: "Enable availability first to send offers.",
      pending: "Pending",
      accepted: "Accepted",
      rejected: "Rejected",
      completed: "Completed",
      inProgress: "In Progress",
      jobAccepted: "Accepted",
      budget: "Customer Budget",
      onSitePayment: "Payment on arrival (cash)",
      request: "Request",
    },
    providerEarnings: {
      title: "Earnings",
      netLabel: "Net Earnings (after commission)",
      servicesDone: "Service Completed",
      grossIncome: "Gross Income",
      platformFee: "Platform Fee (10%)",
      netEarnings: "Net Earnings",
      commissionOwed: "Commission Owed to Platform",
      commissionBreakdown: "Total commission {total} SAR \u00b7 Settled {settled} SAR",
      noCommission: "No commission owed to you right now",
      threshold: "Allowed threshold: {threshold} SAR",
      commissionWarning: "You exceeded the allowed commission threshold. You cannot receive new requests until you settle the owed amount via platform admin.",
      history: "Payment History",
      noEarnings: "No earnings yet. Complete your services to see them here.",
      from: "from",
      currency: "SAR",
      request: "Request",
    },
    navigate: {
      arrived: "You have arrived at the customer's location",
      continueTo: "Continue towards the customer",
      after: "after",
      arrivalTime: "Arrival",
      estimatedTime: "Estimated Time",
      remainingDistance: "Remaining Distance",
      voiceNav: "Voice Navigation",
      noLocation: "No location available for this request",
      back: "Back",
      permDenied: "Location permission is required to start navigation",
      locating: "Getting your location...",
      distance: "Distance",
      eta: "ETA",
      approxTime: "Approx. Time",
    },
    providers: {
      title: "Providers",
      latest: "Latest",
      price: "Price",
      nearest: "Nearest",
      topRated: "Top Rated",
      reviews: "reviews",
      km: "km",
      filter: "Filter",
      count: "{{count}} providers",
      mapView: "Map View",
      empty: "No providers found",
      changeLocation: "Change Location",
      availableNow: "Available Now",
      general: "General Maintenance",
      cityFallback: "Nazareth",
      viewProfile: "View Profile",
      requestService: "Request Service",
      searchPlaceholder: "Search for a provider...",
    },
    privacy: {
      title: "Privacy Policy",
      content: "We respect your privacy. We do not sell your data. We only use it to provide the service and facilitate communication between you and service providers.",
    },
    terms: {
      title: "Terms of Use",
      content: "By using Khadma, you agree to communicate in good faith, rate providers after completion, and pay upon delivery if agreed.",
    },
    about: {
      title: "About the App",
      content: "Khadma \u2014 a smart app for booking home and personal services in northern Israel. We connect you with the best providers with trust and safety.",
    },
  },
  he: {
    dir: "rtl" as const,
    flag: "🇮🇱",
    label: "עברית",
    tabs: { home: "בית", services: "שירותים", request: "בקשה", orders: "הזמנות", profile: "פרופיל", more: "עוד" },
    langPicker: {
      title: "בחר את השפה שלך",
      subtitle: "בחר את השפה המתאימה לך",
      arabic: "ערבית",
      english: "אנגלית",
      hebrew: "עברית",
      rtl: "מימין לשמאל",
      ltr: "שמאל לימין",
    },
    onboarding: {
      skip: "דיגו",
      next: "הבא",
      startNow: "התחל עכשיו",
      slide1Label: "בחר את הדרך שלך",
      slide1Desc: "ספק שירותים או לקוח",
      slide2Label: "גלה ספקים",
      slide2Desc: "הספקים הטובים ביותר",
      slide3Label: "עיין בשירותים",
      slide3Desc: "מגוון רחב של שירותי בית",
      slide4Label: "הזמן בקלות",
      slide4Desc: "צעדים פשוטים להזמנת שירות",
    },
    auth: {
      appName: "Khadma",
      welcomeBack: "ברוך הבא",
      signIn: "התחבר",
      signInSub: "הזן את פרטייך להמשיך",
      signUp: "הירשם",
      signUpSub: "הירשם כדי להתחיל להשתמש ב-Khadma",
      verifyEmail: "אימות אימייל",
      verifySub: "הזן את קוד האימות שנשלח לדואר האימייל שלך",
      email: "אימייל",
      password: "סיסמה",
      code: "קוד אימות",
      enter: "התחבר",
      verify: "אמת והתחבר",
      create: "הירשם",
      sendCode: "שלח קוד",
      sending: "שולח...",
      verifying: "מאמת...",
      resend: "שלח שוב את הקוד",
      or: "או",
      signInGoogle: "התחבר דרך Google",
      signUpGoogle: "הירשם דרך Google",
      hasAccount: "כבר יש לך חשבון?",
      noAccount: "אין לך חשבון?",
      loginLink: "התחבר",
      registerLink: "הירשם",
      back: "חזור",
      changeEmail: "שנה אימייל",
      completeProfile: "השלם את הפרופיל שלך",
      fullName: "שם מלא",
      namePlaceholder: "הזן את שמך",
      howToUse: "איך תרצה להשתמש?",
      customer: "מבקש שירות",
      provider: "מספק שירות",
      commissionTitle: "עמלת הפלטפורמה",
      commissionText: "הפלטפורמה גובה 10% מהשירות. סכום זה מווז אוטומטית מהרווחה והפרטים מופיעים בדף ההכנסות.",
      commissionAgree: "אני מסכים לעמלה של 10% מההכנסות",
      continue: "המשך",
      saving: "משמר...",
      logout: "התנתק",
      nameError: "אנא הזן את שמך",
      commissionError: "יש להסכים לעמלת הפלטפורמה (10%) כדי להמשיך",
      agreementsError: "יש להסכים לכל הסעיפים כדי להמשיך",
      privacyAgree: "אני מסכים למדיניות הפרטיות",
      privacyRead: "קריאה",
      pledgeAgree: "אני מאשר את נכונות פרטיי ומתחייב לספק שירותים במקצועיות, בכבוד ובהתאם למועדים שנקבעו",
      privacyTitle: "מדיניות פרטיות",
      privacyBody:
        "חדמה מחברת בין נותני שירותי בית ושירותים אישיים לבין לקוחות בצפון הארץ. הפרטיות שלך חשובה לנו, וכך אנו מטפלים בנתונים שלך:\n\n" +
        "1) מידע שאנו אוספים: שם, מספר טלפון, דוא\"ל, כתובת ומיקום, ומסמכי אימות לנותני שירות כגון רישיון עסק ותעודת זהות.\n\n" +
        "2) כיצד אנו משתמשים בו: ליצירת החשבון, התאמה לנותן השירות המתאים הקרוב, טיפול בבקשות ובתשלומים ויצירת קשר בנוגע לשירות.\n\n" +
        "3) שיתוף מידע: אנו משתפים רק את הנדרש להשלמת השירות (כגון שמך ומיקומך המשוער עם נותן השירות). איננו מוכרים את הנתונים שלך לצד שלישי.\n\n" +
        "4) מיקום: משמש להצגת נותני שירות קרובים והגדרת אזורי שירות. ניתן לכבותו בהגדרות המכשיר.\n\n" +
        "5) מסמכי אימות: נשמרים באופן מאובטח, משמשים רק לבדיקת בקשת הצטרפות ונמחקים לאחר ההחלטה הסופית.\n\n" +
        "6) הזכויות שלך: ניתן לערוך את המידע או לבקש מחיקת החשבון בכל עת.\n\n" +
        "7) יצירת קשר: לכל שאלה בנושא פרטיות פנה אלינו דרך עמוד \"צור קשר\" באפליקציה.",
      privacyClose: "סגירה",
      provisionError: "לא ניתן ליצור פרופיל, נסה שוב",
      serverError: "לא ניתן התחברות לשרת, בדוק את החיבור",
      invalidCode: "קוד שגוי או פג תוקף, נסה שוב",
      loginFailed: "לא ניתן להשלים את ההתחברות, נסה שוב",
      signupFailed: "לא ניתן להשלים את ההרשמה, נסה שוב מאוחר יותר",
      verifyFailed: "לא ניתן לאמת את הקוד, נסה שוב",
      finalizeFailed: "לא ניתן להשלים את ההתחברות, נסה שוב",
    },
    role: {
      appName: "Khadma",
      welcome: "ברוך הבא",
      subtitle: "בחר את סוג החשבון המתאים לך",
      provider: "ספק שירות",
      providerDesc: "הצטרף כספק שירות והצע את השירותים שלך ללקוחות",
      customer: "מבקש שירות",
      customerDesc: "בקש את השירותים שאתה צריך בקלות ובבטחה",
      contact: "צור קשר",
      contactSub: "אנחנו כאן לעזור",
    },
    home: {
      appName: "Khadma",
      goodEvening: "ערב טוב",
      weAreHere: "אנחנו כאן לשרת אותך במקצועיות",
      currentLocation: "המיקום הנוכחי שלך",
      update: "עדכון",
      locationDenied: "הרשאת המיקום נדחתה. הפעל אותה בהגדרות המכשיר כדי להמשיך.",
      openSettings: "פתח הגדרות",
      locationError: "לא ניתן לאתר את מיקומך הנוכחי. ודא ששירותי המיקום פעילים ונסה שוב.",
      searchService: "חפש שירות...",
      viewAll: "הצג הכל",
      categories: "קטגוריות",
      professionalServices: "שירותים מקצועיים",
      highQuality: "באיכות גבוהה במחירים הוגנים",
      bookNow: "הזמן עכשיו",
      painting: "צבע",
      maintenance: "תחזוקת בתים",
      electricity: "חשמל",
      plumbing: "אינסטלציה",
      furniture: "רהיטים ועיצוב",
      cars: "שירותי רכב",
      cleaning: "ניקיון",
      ac: "מיזוג אוויר",
      carpentry: "נגרות",
      appliances: "מכשירי חשמל",
      pest_control: "הדברה",
      landscaping: "גינון",
      moving: "הובלה",
      other: "שירותים אחרים",
    },
    services: {
      title: "שירותים",
      beauty: "יופי",
      home: "בית",
      maintenance: "תיקונים",
      added: "נוסף",
      add: "בקש",
      min: "דק׳",
      currency: "₪",
      empty: "לא נמצאו שירותים",
    },
    req: {
      newTitle: "בקשת שירות",
      newSub: "תאר את מה שאתה צריך וקבל הצעות מספקים",
      chooseService: "בחר שירות",
      details: "פרטים",
      descLabel: "תיאור הבקשה",
      descPlaceholder: "תאר את מה שאתה צריך...",
      photo: "תמונה (אופציונלי)",
      addPhoto: "הוסף תמונה",
      changePhoto: "החלף תמונה",
      removePhoto: "הסר",
      uploading: "מעלה תמונה...",
      location: "מיקום",
      useGps: "השתמש במיקומי הנוכחי",
      locating: "מאתר מיקום...",
      located: "המיקום נקבע",
      addressPlaceholder: "כתובת או תיאור מיקום",
      priceRange: "טווח מחירים צפוי",
      priceMin: "מ-",
      priceMax: "עד",
      preferredTime: "זמן מועדף",
      timeAsap: "בהקדם האפשרי",
      timeTodayEve: "היום בערב",
      timeTomMorning: "מחר בבוקר",
      timeTomEve: "מחר בערב",
      submit: "שלח בקשה",
      submitting: "שולח...",
      created: "הבקשה נשלחה",
      createdMsg: "ספקים ייצרו איתך קשר עם ההצעות שלהם בקרוב",
      viewRequest: "צפה בבקשה",
      ok: "אישור",
      selectServiceFirst: "בחר שירות תחילה",
      locationRequired: "אנא הזן את שם היישוב או העיר",
      phoneRequired: "אנא הזן מספר טלפון תקין",
      paymentLabel: "אמצעי תשלום (אופציונלי)",
      payOnSite: "תשלום במקום (מזומן)",
      error: "לא ניתן לשלוח את הבקשה. נסה שוב.",
      currency: "₪",
      mediaSectionTitle: "צרוף תמונה או סירטון (חובה)",
      mediaSectionSub: "צרוף קובץ אחד לפחות להבהר את הבקשה",
      mediaRequired: "אנא צרוף תמונה או סירטון לבקשה",
      photoBtn: "תמונה",
      videoBtn: "סירטון",
      uploadingMedia: "מעלה קובץ...",
      sparePartsLabel: "כולל חלקי חילוף",
      sparePartsHint: "אופציונלי — סמן אם העבודה כוללת חלקי חילוף",
      mediaPermission: "נדרשת הרשאת גישה למדיה",
      stepLocation: "איפה אתה זקוק לשירות?",
      stepDescription: "מה צריך שיעשו?",
      stepTime: "מתי אתה זקוק לזה?",
      stepPrice: "מה התקציב שלך?",
      next: "הבא",
      back: "חזור",
      confirm: "אישור ושליחה",
      review: "סקירה",
      changeService: "שינוי שירות",
      request: "בקשה",
      myTitle: "הבקשות שלי",
      current: "בקשות פעילות",
      past: "בקשות קודמות",
      empty: "אין בקשות עדיין",
      emptySub: "בקש את השירות הראשון שלך עכשיו",
      newRequest: "בקשה חדשה",
      requestDetails: "פרטי הבקשה",
      offers: "הצעות",
      offersFor: "הצעות שהתקבלו",
      noOffers: "אין הצעות עדיין",
      noOffersSub: "ממתין שספקים ישלחו הצעות",
      offersError: "טעינת ההצעות נכשלה",
      offersRetry: "נסה שוב",
      offerCount: "הצעות",
      chooseOffer: "בחר הצעה זו",
      choosing: "מקבל...",
      accepted: "התקבלה",
      rejected: "נדחתה",
      pendingOffer: "ממתין",
      chosenProvider: "הספק הנבחר",
      scheduledFor: "מועד",
      rating: "דירוג",
      noRating: "חדש",
      offerMessage: "הודעה",
      availableTime: "זמן זמין",
      duration: "משך",
      provider: "ספק",
      confirmAccept: "קבל הצעה",
      confirmAcceptMsg: "הספק הזה יוקצה ושאר ההצעות יידחו.",
      cancelRequest: "בטל בקשה",
      cancelConfirm: "האם אתה בטוח שברצונך לבטל בקשה זו?",
      markComplete: "סמן כהושלם",
      completeConfirm: "האם השירות הושלם בהצלחה?",
      cancel: "ביטול",
      statusPending: "ממתין להצעות",
      statusActive: "התקבל",
      statusInProgress: "בביצוע",
      statusCompleted: "הושלם",
      statusCancelled: "בוטל",
      tlCreated: "הבקשה נוצרה",
      tlActive: "נבחר ספק",
      tlCompleted: "השירות הושלם",
    },
    profile: {
      title: "הפרופיל שלי",
      name: "משתמש חדמה",
      verified: "מאומת",
      completed: "הושלם",
      active: "פעיל",
      total: "סה״כ בקשות",
      accountSection: "חשבון",
      nameLabel: "שם",
      phoneLabel: "טלפון",
      addresses: "הכתובות שלי",
      addressTitle: "הכתובת שלי",
      addressDesc: "המיקום נשמר ומשמש אוטומטית בכל בקשה חדשה, ולא משתנה אלא אם תשנה אותו בעצמך.",
      addressLabel: "כתובת",
      addressPlaceholder: "לדוגמה: שפרעם, הרובע המזרחי, רחוב 12",
      addressEmpty: "טרם הוגדרה כתובת",
      addressSaved: "הכתובת נשמרה",
      saveAddress: "שמירת כתובת",
      editProfile: "עריכת פרופיל",
      save: "שמור",
      saving: "שומר...",
      nameHint: "השם הוא רשות",
      phoneHint: "ניתן לשנות את מספר הטלפון בכל עת",
      updated: "הפרופיל עודכן",
      updateFailed: "העדכון נכשל, נסה שוב",
      prefs: "העדפות",
      notifications: "התראות",
      language: "שפה",
      theme: "מראה",
      dark: "כהה",
      light: "בהיר",
      support: "תמיכה",
      faq: "שאלות נפוצות",
      contact: "צור קשר",
      rate: "דרג את האפליקציה",
      logout: "התנתק",
      logoutConfirm: "האם אתה בטוח שברצונך להתנתק?",
      logoutTitle: "התנתק",
      cancel: "ביטול",
      version: "Khadma • גרסה 1.0.0",
    },
    review: {
      rateProvider: "דרג ספק",
      title: "דרג את השירות",
      subtitle: "איך הייתה החוויה שלך עם הספק?",
      commentLabel: "תגובה (אופציונלי)",
      commentPlaceholder: "שתף את דעתך על השירות...",
      submit: "שלח דירוג",
      submitting: "שולח...",
      submitted: "הדירוג נשלח",
      thanks: "תודה על הדירוג!",
      alreadyReviewed: "כבר דירגת שירות זה",
      yourReview: "הדירוג שלך",
      selectStars: "בחר דירוג",
      error: "לא ניתן לשלוח את הדירוג. נסה שוב.",
    },
    notif: {
      title: "התראות",
      empty: "אין התראות",
      emptySub: "עדכונים על הבקשות וההצעות שלך יופיעו כאן",
      markAllRead: "סמן הכל כנקרא",
      error: "טעינת ההתראות נכשלה",
      retry: "נסה שוב",
    },
    chat: {
      title: "הודעות",
      empty: "אין שיחות",
      emptySub: "השיחות שלך עם נותני השירות יופיעו כאן",
      error: "טעינת השיחות נכשלה",
      threadError: "טעינת השיחה נכשלה",
      retry: "נסה שוב",
      inputPlaceholder: "כתוב הודעה...",
      send: "שלח",
      messageProvider: "שלח הודעה לספק",
      messageCustomer: "שלח הודעה ללקוח",
      startConversation: "התחל את השיחה בשליחת הודעה",
      requestLabel: "בקשה",
      requestFallback: "בקשה",
      customerPhone: "טלפון הלקוח",
      providerPhone: "טלפון נותן השירות",
      callCustomer: "התקשר ללקוח",
      callProvider: "התקשר לנותן השירות",
      contactAfterAccept: "מספר הטלפון מוצג לאחר אישור הבקשה",
    },
    contact: {
      title: "צור קשר",
      subtitle: "נשמח לשמוע את המשוב והשאלות שלך",
      nameLabel: "שם",
      emailLabel: "אימייל (אופציונלי)",
      subjectLabel: "נושא (אופציונלי)",
      messageLabel: "ההודעה שלך",
      namePlaceholder: "השם שלך",
      emailPlaceholder: "you@example.com",
      subjectPlaceholder: "נושא ההודעה",
      messagePlaceholder: "כתוב את ההודעה שלך כאן...",
      submit: "שלח",
      submitting: "שולח...",
      sent: "ההודעה נשלחה",
      sentMsg: "נחזור אליך בהקדם האפשרי",
      error: "לא ניתן לשלוח את ההודעה. נסה שוב.",
      required: "אנא הזן שם והודעה",
    },
    rate: {
      title: "דרג את האפליקציה",
      subtitle: "המשוב שלך עוזר לנו לשפר את חדמה",
      tapToRate: "הקש על הכוכבים לדירוג",
      commentLabel: "המשוב שלך (אופציונלי)",
      commentPlaceholder: "מה אתה אוהב או מה נוכל לשפר?",
      submit: "שלח דירוג",
      submitting: "שולח...",
      sent: "תודה!",
      sentMsg: "הדירוג שלך נשלח בהצלחה",
      error: "לא ניתן לשלוח את הדירוג. נסה שוב.",
      selectStars: "אנא בחר דירוג תחילה",
      appRatingSubject: "דירוג האפליקציה",
    },
    ranking: {
      title: "הספקים המובילים",
      subtitle: "המדורגים הגבוה ביותר על ידי הלקוחות שלנו",
      empty: "אין ספקים עדיין",
      reviews: "ביקורות",
      jobs: "עבודות",
      noRating: "חדש",
    },
    providerOnboarding: {
      title: "הירשם כספק",
      subtitle: "השלם את הפרטים שלך כדי להתחיל לקבל בקשות",
      serviceLabel: "השירות שאתה מספק",
      cityLabel: "היישוב אתה משרת",
      cityPlaceholder: "בחר יישוב",
      phoneLabel: "מספר טלפון",
      phonePlaceholder: "05X XXX XXXX",
      experienceLabel: "שנות ניסיון",
      experiencePlaceholder: "לדוגמה: 5",
      bioLabel: "אודותיך ומה אתה מספק",
      bioPlaceholder: "תאר את השירות שלך، התמחות ומה מייחד אותך...",
      locationLabel: "המיקום שלך (אופציונלי)",
      locationBtn: "אתר את המיקום הנוכחי שלי",
      locationDone: "המיקום נקבע",
      submit: "שלח בקשת הרשמה",
      errorService: "אנא בחר את השירות שאתה מספק",
      errorCity: "אנא בחר את היישוב אתה משרת",
      errorPhone: "אנא הזן את מספר הטלפון",
      errorSubmit: "לא ניתן לשלוח את הבקשה. נסה שוב.",
      errorLocation: "לא ניתן לאתר את המיקום. הפעל את שירותי המיקום ונסה שוב.",
      errorCustomSkill: "שגיאה בהוספת מיומנות. נסה שוב.",
      logout: "התנתק",
      skillsLabel: "מיומנויות שאתה מציע",
      addCustomSkill: "מיומנות מותאמת אישית",
      customSkillTitle: "הוסף מיומנות מותאמת אישית",
      customSkillPlaceholder: "שם המיומנות...",
      cityModalTitle: "בחר יישוב",
      cityModalSearch: "חפש יישוב...",
      cityModalEmpty: "אין תוצאות",
      skillsPlaceholder: "בחר את השירותים שלך...",
      skillsSelectedSuffix: "שירותים נבחרו",
      skillsModalTitle: "בחר את השירותים שלך",
      skillsModalSearch: "חפש שירות...",
      skillsModalEmpty: "אין תוצאות",
      skillsModalDone: "סיום",
      addressLabel: "כתובת מגורים",
      addressPlaceholder: "עיר, רחוב, מספר בית",
      errorAddress: "אנא הזן את כתובת המגורים",
      docsLabel: "מסמכים נדרשים",
      docsHint: "משמשים לאימות בלבד ונמחקים לאחר הבדיקה",
      docOsekPaturLabel: "אישור עוסק פטור",
      docOsekMursheLabel: "אישור עוסק מורשה",
      docIdLabel: "תמונת תעודת זהות או רישיון",
      docRequired: "חובה",
      docOptional: "אופציונלי",
      docPick: "צרף קובץ",
      docReplace: "החלף קובץ",
      docOnFile: "צורף",
      docSaved: "שמור אצל ההנהלה",
      docUploading: "מעלה...",
      errorDocs: "אנא צרף את כל המסמכים הנדרשים",
      docUploadError: "לא ניתן להעלות את הקובץ. נסה שוב.",
      reviewNoteTitle: "הערה מההנהלה",
      resubmit: "שלח מחדש את הבקשה",
      resubmitTitle: "עדכן את הפרטים שלך",
      resubmitSubtitle: "עדכן את המידע או המסמכים הנדרשים ושלח מחדש",
    },
    providerDashboard: {
      title: "לוח",
      requests: "בקשות",
      greeting: "היי {name}",
      guest: "אורח",
      availOn: "זמין",
      availOff: "לא זמין",
      receiveRequests: "קבל בקשות",
      visibleNow: "אתה נראה ללקוחות עכשיו",
      activateAvail: "הפעל זמינות כדי לקבל בקשות",
      workHours: "שעות עבודה",
      from: "מ",
      to: "עד",
      saveHours: "שמור שעות עבודה",
      completed: "הושלם",
      active: "פעיל",
      earnings: "SAR",
      openRequests: "בקשות פתוחות",
      seeAll: "ראה הכל",
      activateAvailHint: "הפעל זמינות כדי לראות בקשות קרובות",
      noMatching: "אין בקשות תואמות לשירות שלך עכשיו",
      request: "בקשה",
    },
    providerProfile: {
      title: "הפרופיל שלי",
      provider: "ספק שירות",
      noRating: "אין דירוגים עדיין",
      service: "הושלם",
      avgRating: "דירוג ממוצע",
      status: "סטטוס",
      statusOpen: "פתוח",
      statusClosed: "סגור",
      account: "חשבון",
      edit: "ערוך",
      name: "שם",
      serviceLabel: "שירות",
      phone: "טלפון",
      address: "כתובת",
      location: "מיקום",
      locationSet: "המיקום נקבע",
      locationNotSet: "לא נקבע",
      workHours: "שעות עבודה",
      bio: "אודות",
      logout: "התנתק",
      logoutConfirm: "האם אתה בטוח שברצונך להתנתק?",
      version: "חדמה · ספק שירות · גרסה 1.0.0",
      editTitle: "ערוך חשבון",
      fullName: "שמך המלא",
      phonePlaceholder: "05X XXX XXXX",
      chooseService: "השירות שאתה מספק",
      addressPlaceholder: "עיר, רחוב, מספר בית",
      detectLocation: "אתר את המיקום הנוכחי שלי",
      locationDetected: "המיקום הנוכחי שלך נקבע",
      saveChanges: "שמור שינויים",
      commissionSection: "עמלת הפלטפורמה",
      commissionRate: "שיעור העמלה",
      commissionDesc: "הפלטפורמה גובה עמלה של 10% מכל שירות שתשלים, המנוכה אוטומטית מההכנסות שלך.",
      commissionAgreedLabel: "תאריך הסכמה",
      commissionNotRecorded: "לא נרשם",
    },
    providerRequests: {
      title: "בקשות",
      tabAvailable: "זמין",
      tabOffers: "ההצעות שלי",
      tabJobs: "עבודות שלי",
      activateFirst: "הפעל זמינות מהדף הראשי כדי לקבל בקשות קרובות",
      noNearby: "אין בקשות קרובות תואמות לשירות שלך כרגע",
      offerSent: "הצעה נשלחה",
      sendOffer: "שלח הצעה",
      noOffers: "עדיין לא שלחת הצעות",
      messageCustomer: "שלח הודעה ללקוח",
      noJobs: "עדיין לא הוסדרו אליך עבודות",
      startJob: "התחל עבודה",
      completeJob: "השלם שירות",
      navigate: "התחל ניווט",
      offerTitle: "שלח הצעה",
      priceLabel: "מחיר (SAR)",
      durationLabel: "משך צפוי (אופציונלי)",
      durationPlaceholder: "לדוגמה: שעה אחת",
      timeLabel: "זמן זמינות",
      messageLabel: "הודעה (אופציונלי)",
      messagePlaceholder: "הצג את עצמך או הוסף פרטים...",
      submitOffer: "שלח הצעה",
      enterPrice: "אנא הזן מחיר תקף.",
      offerError: "לא ניתן לשלוח את ההצעה. נסה שוב.",
      offerAvailError: "הפעל זמינות קודם כדי לשלוח הצעות.",
      pending: "ממתין",
      accepted: "מאושר",
      rejected: "נדחה",
      completed: "הושלם",
      inProgress: "בתהליך",
      jobAccepted: "מאושר",
      budget: "תקציב הלקוח",
      onSitePayment: "תשלום בגעת (מזומן)",
      request: "בקשה",
    },
    providerEarnings: {
      title: "הכנסות",
      netLabel: "הכנסות נטו (אחרי עמלה)",
      servicesDone: "שירות הושלם",
      grossIncome: "הכנסה ברוטו",
      platformFee: "עמלת פלטפורמה (10%)",
      netEarnings: "הכנסות נטו",
      commissionOwed: "עמלה חייבת לפלטפורמה",
      commissionBreakdown: "עמלה כוללת {total} SAR \u00b7 שולם {settled} SAR",
      noCommission: "אין עמלה חייבת כרגע",
      threshold: "סף מותר: {threshold} SAR",
      commissionWarning: "חרגת מהסף המותר. לא תוכל לקבל בקשות חדשות עד שתשלם את הסכום החייב דרך הנהלת הפלטפורמה.",
      history: "היסטוריית תשלומים",
      noEarnings: "אין הכנסות עדיין. השלם את השירותים שלך כדי לראות אותם כאן.",
      from: "מ",
    },
    navigate: {
      arrived: "הגעת למיקום הלקוח",
      continueTo: "המשך לכיוון הלקוח",
      after: "אחרי",
      arrivalTime: "הגעה",
      estimatedTime: "זמן משוער",
      remainingDistance: "מרחק נותר",
      voiceNav: "ניווט קולי",
    },
    providers: {
      title: "ספקים",
      latest: "האחרונים",
      price: "מחיר",
      nearest: "הקרובים",
      topRated: "המדורגים ביותר",
      reviews: "ביקורות",
      km: "קמ",
      filter: "סנן",
      count: "{{count}} ספקים",
      mapView: "תצוגת מפה",
      empty: "לא נמצאו ספקים",
      changeLocation: "שינוי מיקום",
      availableNow: "זמין עכשיו",
      general: "תחזוקה כללית",
      cityFallback: "נצרת",
      viewProfile: "צפה בפרופיל",
      requestService: "בקש שירות",
    },
    privacy: {
      title: "מדיניות פרטיות",
      content: "אנו מכבדים את פרטיותך. איננו מוכרים את נתוניך. אנו משתמשים בהם רק לצורך מתן השירות ולתקשורת בינך לבין ספקי השירות.",
    },
    terms: {
      title: "תנאי שימוש",
      content: "בשימוש בחדמה, הנך מסכים לתקשורת בתום לב, לדרג ספקים לאחר השלמת השירות, ולשלם בעת המסירה במידה וסוכם על כך.",
    },
    about: {
      title: "אודות האפליקציה",
      content: "חדמה — אפליקציה חכמה להזמנת שירותי בית ואישיים בצפון ישראל. אנו מחברים אותך עם הספקים הטובים ביותר באמון ובבטיחות.",
    },
  },
};

type T = typeof translations.ar;

interface LanguageContextType {
  lang: Lang;
  t: T;
  setLang: (l: Lang) => void;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>("ar");

  useEffect(() => {
    (async () => {
      try {
        const saved = await AsyncStorage.getItem(LANG_STORAGE_KEY);
        if (saved === "ar" || saved === "en" || saved === "he") {
          setLangState(saved);
        }
      } catch {
        // ignore — keep the default language
      }
    })();
  }, []);

  const setLang = (l: Lang) => {
    setLangState(l);
    AsyncStorage.setItem(LANG_STORAGE_KEY, l).catch(() => {});
  };

  const t = translations[lang] as T;
  const isRTL = t.dir === "rtl";

  return (
    <LanguageContext.Provider value={{ lang, t, setLang, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLang must be inside LanguageProvider");
  return ctx;
}
